# Generated by Django 2.2.1 on 2019-05-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of user registration')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Date of user last activity')),
                ('active', models.BooleanField(default=True, verbose_name='Is the user is available')),
            ],
        ),
    ]
