# Generated by Django 2.2.1 on 2019-05-10 12:23

from django.db import migrations, models
import rooms.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=rooms.manager.RoomManager.get_room_name, max_length=128, verbose_name='Room name')),
                ('description', models.TextField(verbose_name='Room description')),
                ('password', models.CharField(max_length=512, verbose_name='Room password hash')),
                ('link', models.CharField(max_length=128, verbose_name='Custom room link')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of room creating')),
            ],
        ),
    ]
