# Generated by Django 2.2.1 on 2019-05-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='messages',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='datetime',
            new_name='created',
        ),
    ]
